// GENERATED by scripts/gen-bindings.ts — DO NOT EDIT.
//
// Source of truth: docs/bible/opcodes/*.md frontmatter (and concept pages that
// bind a glyph). Change a name or an emoji THERE, then run:
//
//     npm run gen:bindings
//
// The mnemonic is the engine's immutable identity; `name` is the friendly
// display name shown in simple mode. The engine's own `gene` token stays the
// compilable form — a rebind changes what a learner reads, never what compiles.

export type BindingCategory = "action" | "register" | "marker" | "control" | "value";

export interface OpcodeBinding {
  readonly mnemonic: string;
  readonly name: string;
  readonly emoji: string;
  readonly category: BindingCategory;
  readonly takesTarget: boolean;
}

export const OPCODE_BINDINGS: Readonly<Record<string, OpcodeBinding>> = Object.freeze({
  adrb: { mnemonic: "adrb", name: "find-back", emoji: "🔎", category: "control", takesTarget: true },
  adrf: { mnemonic: "adrf", name: "find-forward", emoji: "🔦", category: "control", takesTarget: true },
  adro: { mnemonic: "adro", name: "find", emoji: "🔍", category: "control", takesTarget: true },
  call: { mnemonic: "call", name: "call", emoji: "📞", category: "control", takesTarget: true },
  decC: { mnemonic: "decC", name: "shrink-c", emoji: "🍂", category: "register", takesTarget: false },
  divide: { mnemonic: "divide", name: "divide", emoji: "👶", category: "control", takesTarget: false },
  ifz: { mnemonic: "ifz", name: "if-zero", emoji: "❓", category: "control", takesTarget: false },
  incA: { mnemonic: "incA", name: "grow-a", emoji: "🌱", category: "register", takesTarget: false },
  incB: { mnemonic: "incB", name: "grow-b", emoji: "🌿", category: "register", takesTarget: false },
  incC: { mnemonic: "incC", name: "grow-c", emoji: "🌳", category: "register", takesTarget: false },
  jmpb: { mnemonic: "jmpb", name: "jump-back", emoji: "⏪", category: "control", takesTarget: true },
  jmpo: { mnemonic: "jmpo", name: "jump", emoji: "⏩", category: "control", takesTarget: true },
  mal: { mnemonic: "mal", name: "make-space", emoji: "🏗️", category: "control", takesTarget: false },
  movBA: { mnemonic: "movBA", name: "copy-a-to-b", emoji: "🔄", category: "register", takesTarget: false },
  movDC: { mnemonic: "movDC", name: "copy-c-to-d", emoji: "🔃", category: "register", takesTarget: false },
  movii: { mnemonic: "movii", name: "copy-byte", emoji: "✂️", category: "action", takesTarget: false },
  nop0: { mnemonic: "nop0", name: "mark-0", emoji: "🔵", category: "marker", takesTarget: false },
  nop1: { mnemonic: "nop1", name: "mark-1", emoji: "🔴", category: "marker", takesTarget: false },
  not0: { mnemonic: "not0", name: "flip-bit", emoji: "🪙", category: "action", takesTarget: false },
  popA: { mnemonic: "popA", name: "load-a", emoji: "📤", category: "register", takesTarget: false },
  popB: { mnemonic: "popB", name: "load-b", emoji: "📂", category: "register", takesTarget: false },
  popC: { mnemonic: "popC", name: "load-c", emoji: "🧲", category: "register", takesTarget: false },
  popD: { mnemonic: "popD", name: "load-d", emoji: "🎣", category: "register", takesTarget: false },
  pushA: { mnemonic: "pushA", name: "save-a", emoji: "📥", category: "register", takesTarget: false },
  pushB: { mnemonic: "pushB", name: "save-b", emoji: "💾", category: "register", takesTarget: false },
  pushC: { mnemonic: "pushC", name: "save-c", emoji: "🧺", category: "register", takesTarget: false },
  pushD: { mnemonic: "pushD", name: "save-d", emoji: "🗄️", category: "register", takesTarget: false },
  ret: { mnemonic: "ret", name: "return", emoji: "🔙", category: "control", takesTarget: false },
  shl: { mnemonic: "shl", name: "double", emoji: "✖️", category: "action", takesTarget: false },
  subAAC: { mnemonic: "subAAC", name: "subtract-into-a", emoji: "🔻", category: "register", takesTarget: false },
  subCAB: { mnemonic: "subCAB", name: "subtract", emoji: "➖", category: "register", takesTarget: false },
  zero: { mnemonic: "zero", name: "clear", emoji: "🧹", category: "action", takesTarget: false },
});

export interface ConceptBinding {
  readonly slug: string;
  readonly name: string;
  readonly emoji: string;
}

export const CONCEPT_BINDINGS: Readonly<Record<string, ConceptBinding>> = Object.freeze({
  label: { slug: "label", name: "label", emoji: "🪧" },
});

/** A friendly name is one word: letters, digits and hyphens only. */
export function isValidName(name: string): boolean {
  return /^[A-Za-z0-9]+(-[A-Za-z0-9]+)*$/.test(name);
}
